### ISSUE TITLE
Implement delivery receipts for PE Report emails

### ISSUE THREAD

**Issue by rapidray12** [cisagov/pe-reports#249] opened 2022-08-26 20:26 UTC
# 💡 Summary #

All reports sent out by the P&E team should request delivery receipts.

## Motivation and context ##

The report mailer is part of this project.  It is the code base that will need to be modified.

This would be useful so that we can tell that the stakeholders Email system isn't rejecting the reports.

## Acceptance criteria ##

Delivery receipts returned for the P&E reports

- [ ] Criterion

**Comment by stewartl97** [comment] 2022-09-02 14:27
Duplicate of Issue-216

**Closed as completed by stewartl97** 2022-09-02 14:27 UTC
