### ISSUE TITLE
Add report_generator to UI

### ISSUE THREAD

**Issue by aloftus23** [cisagov/pe-reports#206] opened 2022-05-19 16:21 UTC
# 💡 Summary #

Add functionality to the UI that allows P&E team members to launch the report generator scripts. Also see #131 

## Implementation notes ##

UI will accept input for the report period date, organization(s), and output location. All of these fields will be required to run the report_generator.

Will need to create a new page in the UI that users can navigate to in the header.

Preferably the UI will display logging output from the report generator scripts.

**Comment by stewartl97** [comment] 2022-08-15 17:23
@aloftus23 what is the current status of this task?

**Comment by cduhn17** [comment] 2022-09-07 13:31
This issue also links to #131

**Comment by stewartl97** [comment] 2022-11-21 14:26
Duplicate of #131

**Closed as completed by stewartl97** 2022-11-21 14:26 UTC
Labels: duplicate, improvement, wontfix
